apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: caywoodridge-web
  namespace: caywoodridge
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: caywoodridge.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caywoodridge-web
                port:
                  number: 80
  tls:
    - hosts:
        - caywoodridge.com
      secretName: caywoodridge-tls
