apiVersion: v1
kind: Service
metadata:
  name: caywoodridge-web
  namespace: caywoodridge
  labels:
    app: caywoodridge-web
spec:
  selector:
    app: caywoodridge-web
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
